# config file version
# Updated per https://grafana.com/docs/grafana/latest/datasources/influxdb/#provision-the-data-source
apiVersion: 1

deleteDatasources:
  - name: Influxdb
    orgId: 1

datasources:
  - name: Influxdb
    type: influxdb
    access: proxy
    user: {{ influx.username }}
    url: http://localhost:8086
    jsonData:
      dbName: {{ influx.bucket }}
      httpMode: GET
    secureJsonData:
      password: {{ influx.password }}

