---
- name: Configure Telegraf
  hosts: all
  become: true
  gather_facts: true
  vars:
    domain: "domain.com"
    influx:
      org: lp
      bucket: lp
      username: lp
      password: LocaFluxCapacity2024
    grafana:
      subpath: 'metrics'
  roles:
    - name: telegraf_config
    - name: fleet_config
